version: "3"

services:
  analyzer:
    build:
      context: ./services/AnalysisPrinter
    container_name: g23-sonar-analyzer
    depends_on:
      - sonar-server
    restart: on-failure
    volumes:
      - "./input:/usr/src"
      - "./output:/usr/out"
    networks:
      - sonar-net
  sonar-server:
    image: sonarqube:latest
    container_name: g23-sonar-server
    restart: on-failure
    ports:
      - "9000:9000"
    networks:
      - sonar-net
  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: g23-sonar-scanner
    restart: on-failure
    depends_on:
      - sonar-server
    environment:
      - "SONAR_HOST_URL=http://sonar-server:9000"
      - "SONAR_LOGIN=admin"
      - "SONAR_PASSWORD=admin"
    volumes:
      - "./input:/usr/src"
      - "./output:/usr/out"
    networks:
      - sonar-net
  commit-analyzer:
    build:
      context: ./services/DataScraper
    container_name: g23-commit-analyzer
    restart: on-failure
    volumes:
      - "./input:/usr/src"
      - "./output:/usr/out"
  pmd-anylzer:
    build:
      context: ./services/PMDAnalyzer
    container_name: g23-pmd-analyzer
    volumes:
      - "./input:/usr/src"
      - "./output:/usr/out"
    command: tail -F anything
  checkstyle-analyzer:
    build:
      context: ./services/Checkstyle/CheckstyleAnalyzer
    container_name: g23-checkstyle-analyzer
    volumes:
      - "./input:/usr/src"
      - "checkstyle_xml:/usr/out"
  checkstyle-printer:
    build:
      context: ./services/Checkstyle/CheckstylePrinter
    depends_on:
      - checkstyle-analyzer
    container_name: g23-checkstyle-printer
    volumes:
      - "checkstyle_xml:/usr/in"
      - "./output:/usr/out"
volumes:
  checkstyle_xml:
    driver: local
networks:
  sonar-net:
    driver: bridge
