version: "3"

services:
  analyzer:
    build:
      context: ./services/AnalysisPrinter
    container_name: sonar-analyzer
    depends_on:
      - sonar-server
    restart: on-failure
    volumes:
      - "./input:/usr/src"
      - "./output:/usr/out"
    networks:
      - sonar-net
  sonar-server:
    image: sonarqube:latest
    container_name: sonar-server
    restart: on-failure
    ports:
      - "9000:9000"
    networks:
      - sonar-net
  sonar-scanner:
    image: sonarsource/sonar-scanner-cli
    container_name: sonar-scanner
    restart: on-failure
    depends_on:
      - sonar-server
    environment:
      - "SONAR_HOST_URL=http://sonar-server:9000"
      - "SONAR_LOGIN=admin"
      - "SONAR_PASSWORD=admin"
    volumes:
      - "./input:/usr/src"
      - "./output:/usr/out"
    networks:
      - sonar-net
  commit-analyzer:
    build:
      context: ./services/DataScraper
    container_name: commit-analyzer
    restart: on-failure
    volumes:
      - "./input:/usr/src"
      - "./output:/usr/out"

networks:
  sonar-net:
    driver: bridge
